"""empty message

Revision ID: 5edc29385e6f
Revises: dc3b8e22310c
Create Date: 2024-03-25 13:30:55.450742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edc29385e6f'
down_revision = 'dc3b8e22310c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('confirmed_on',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('confirmed_on',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
